server.port: 9999
spring:
  rabbitmq:
    host: 10.138.30.20
    port: 5672
    username: guest
    password: guest
  cloud.stream:
    bindings.output:
      destination: payment.loan.api
      producer:
        partitionKeyExtractorClass: org.molecule.demo.spring.cloud.stream.messagesender.MyExtractor
        partitionCount: 100
        prefix: payment