
spring:
  rabbitmq:
    host: 10.138.30.20
    port: 5672
    username: guest
    password: guest
  cloud.stream:
    instanceIndex: 5
    bindings.input:
      destination: payment.loan.api
      group: result
      consumer.partitioned: true
    rabbit.bindings:
      input.consumer:
        bindingRoutingKey: payment.loan.api
