
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtualHost: /
  cloud:
    stream:
      bindings:
        input:
          destination: payment
          group: my-group